LLM_TEMPERATURE=0.1
LLM_MAX_TOKENS=512

# News provider (optional)
NEWS_ENABLED=false
NEWS_PROVIDER=
NEWS_API_KEY=
NEWS_MAX_HEADLINES=10

# Risk and runtime controls
MAX_LEVERAGE=20.0
MAX_POSITION_NOTIONAL=1000
MAX_DAILY_LOSS=500.0
DRY_RUN=true
POLL_INTERVAL_SECONDS=60
RUN_ONCE=true